services:
  - type: web
    name: ntumai-backend
    env: node
    plan: starter
    buildCommand: |
      npm ci
      npx prisma generate --schema=database/prisma/schema.prisma
      npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ntumai-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

databases:
  - name: ntumai-db
    databaseName: ntumai
    user: ntumai_user
    plan: starter